application: idle-heroes
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
# Endpoints handler
- url: /_ah/spi/.*
  script: main.application

libraries:
- name: endpoints
  version: 1.0