## battletest.py Use this to test out the battle functions

from battle import *
from monster import *

hero_actor = {
  ACTOR_STAT.HEALTH: 100,
  ACTOR_STAT.ACCURACY: 20,
  ACTOR_STAT.DEFENSE: 20,
  ACTOR_STAT.THRUST_RESISTANCE: 0,
  ACTOR_STAT.SLASH_RESISTANCE: 0,
  ACTOR_STAT.CRUSH_RESISTANCE: 0,
  ACTOR_STAT.LIGHTNING_RESISTANCE: 0,
  ACTOR_STAT.FIRE_RESISTANCE: 0,
  ACTOR_STAT.COLD_RESISTANCE: 0,
  ACTOR_STAT.POISON_RESISTANCE: 0,
  ACTOR_STAT.THRUST_DAMAGE: None,
  ACTOR_STAT.SLASH_DAMAGE: (1, 4),
  ACTOR_STAT.CRUSH_DAMAGE: None,
  ACTOR_STAT.LIGHTNING_DAMAGE: None,
  ACTOR_STAT.FIRE_DAMAGE: None,
  ACTOR_STAT.COLD_DAMAGE: None,
  ACTOR_STAT.POISON_DAMAGE: None,
  ACTOR_STAT.THORNS_DAMAGE: None,
  ACTOR_STAT.NAME: 'Hero'
}

getBattleResult(hero_actor, MONSTER.RAT, True)